# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OwFJ5weOGWy41GZzMJLvkS6Ni1amWfv
"""

for i in range(1, 11):
  if i % 2 == 0:
    print("Esta é a repetição de 1 a 10 somente dos números pares: ", i)