# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OwFJ5weOGWy41GZzMJLvkS6Ni1amWfv
"""

def par_ou_impar(numero):
    if numero % 2 == 0:
      return "O número é par"
    else:
      return "O número é ímpar"

numero = int(input("Digite um número: "))
resultado = par_ou_impar(numero)
print(resultado)