# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OwFJ5weOGWy41GZzMJLvkS6Ni1amWfv
"""

filme = input("Qual é o seu filme favorito? ") # Pergunta o filme favorito
ano = input("Em que ano ele foi lançado? ") # Pergunta o ano de lançamento
print("Meu filme favorito é " + filme + " e ele foi lançado em " + ano + " .") # Imprime a mensagem