# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OwFJ5weOGWy41GZzMJLvkS6Ni1amWfv
"""

lista_de_compras = []

while True:
    item = input("Digite um item para adicionar a lista de compras (ou digite fim para terminar): ")
    if item == "fim":
        break
    lista_de_compras.append(item)

print("\nSua lista de compras:")
for item in lista_de_compras:
    print(item)