# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OwFJ5weOGWy41GZzMJLvkS6Ni1amWfv
"""

nome = "Victor"
cidade_natal = "Rio de Janeiro"
print("Meu nome é", nome, "e eu sou de", cidade_natal) # Imprime a mensagem