# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OwFJ5weOGWy41GZzMJLvkS6Ni1amWfv
"""

soma = 0
num = None

while num != 0:
  num = int(input("Digite um número (0 para parar): "))
  soma += num

print("A soma dos números é:", soma)